[package]
name = "sudoku-solver"
version = "0.0.4-dev"
edition = "2021"

[lib]
name = "libsolver"

[dependencies]

[dev-dependencies]
iai-callgrind = "0.10.2"

[[bench]]
name = "dfs-iai"
harness = false
